#!/bin/bash

sudo apt-get update
sudo apt-get install -y
sudo apt autoremove -y
sudo apt install update-manager-core -y
sudo do-release-upgrade -d -y
sudo apt-get -y dist-upgrade --auto-remove --purge
sudo apt-get clean -y
clear
echo -e "\e[1;32m Update Complete \e[0m"
